apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 4Gi  # You can adjust the size as per your needs
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres"  # This path is used in local environments
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi  # Match this with the PV size
