apiVersion: v1
kind: Service
metadata:
  name: todo-worker-service
  labels:
    app: todo-worker
spec:
  type: ClusterIP
  selector:
    app: todo-worker
  ports:
    - protocol: TCP
      port: 80  # This port can be internal since we don't need external access
